### ISSUE TITLE
Cannot create Interactions

### ISSUE THREAD

**Issue by MichelleKubier** [studer-raimann/H5P#9]
We use the Plugin with ILIAS 5.3.6. After uploading or embedding a video, we cannot create any interactions as we get the message "No Video Source". It is possible to create a summery task though, and for users to play the video. Any ideas what´s wrong here?

![interactive_video_no_source](https://user-images.githubusercontent.com/32267686/43317819-e0da97bc-918d-11e8-84fb-bfe991583bfc.png)

**Comment by MichelleKubier** [comment]
![h5p_error](https://user-images.githubusercontent.com/32267686/43393460-bdef9030-93e6-11e8-9d7c-826541f25348.png)
This is the thrown error. Any advice?

**Comment by theodortruffer** [comment]
Hello and sorry for the late answer. I created a ticket in our internal ticket system for this bug. Unfortunately I can't promise you, when this will be looked at - we can't prioritize bug fixing of this plugin, since we have to prioritize plugins of our hosting/SLA customers. But I will inform you as soon as we had the chance to have a look at it.

**Comment by theodortruffer** [comment]
This bug is solved with the library version 1.19.5. Please try to update the library in the plugin configuration if you experience this bug.
